### ISSUE TITLE
CPU vs GPU Inference

### ISSUE THREAD

**Issue by BlueprintBen** [torinos-yt/BlazePoseBarracuda#1]
Thanks for the project - love keijiro's work and seeing it extended!

I was hoping for confirmation on which in this set of models are running on the CPU vs the GPU and what the path would look like to achieve inference purely on the GPU if not already there. I can see a heavy load on the CPU and so am unable to hit 30fps in testing so am curious if it'll be achievable in the future (by myself or others).

Cheers

**Comment by torinos-yt** [comment]
BlazePoseBarracuda is already running most of the processing (including inference and any necessary pre/post processing) on the GPU. In my environment, the bulk of the CPU load comes from dispatching the compute shaders inside the Barracuda package.

**Comment by torinos-yt** [comment]
- What are the specs of your computer?
- Does it reproduce with other keijiro's Barracuda projects?

**Comment by BlueprintBen** [comment]
After more investigation I am thinking that the Deep Profiling actually had a far bigger performance impact than the Barracuda operations themselves and was skewing my understanding of the bottlenecks. With Deep profiling Off I'm seeing much more expected results from the CPU and GPU. I've tested with an RTX 6000 and a GTX 960M now.
